version: '3'

services:
  spark-master:
#    image: aizen_spark:230905
    build: ./spark/linux_os/
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    user: root
    volumes:
      - type: bind
        source: ./spark/conf/log4j.properties
        target: /opt/aizen/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/aizen/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/aizen/spark/ivy:z
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - net

  spark-worker1:
#    image: aizen_spark:230905
    build: ./spark/linux_os/
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    user: root
    volumes:
      - type: bind
        source: ./spark/conf/log4j.properties
        target: /opt/aizen/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/aizen/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/aizen/spark/ivy:z
    ports:
      - '8081:8081'   
    networks:
      - net
    depends_on:
      - spark-master

  spark-worker2:
#    image: aizen_spark:230905
    build: ./spark/linux_os/
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    user: root
    volumes:
      - type: bind
        source: ./spark/conf/log4j.properties
        target: /opt/aizen/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/aizen/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/aizen/spark/ivy:z
    ports:
      - '8082:8082'   
    networks:
      - net
    depends_on:
      - spark-master

  livy-server:
    container_name: livy_server
    build: ./livy-server/
    command: ["sh", "-c", "/opt/aizen/livy/bin/livy-server"]
    user: root
    volumes:
      - type: bind
        source: ./livy/livy-server/conf/
        target: /opt/aizen/livy/conf/
#      - type: bind
#        source: ./livy/livy-server/target/
#        target: /target/
#      - type: bind
#        source: ./livy/livy-server/data/
#        target: /data/
    ports:
      - '8998:8998'
    networks:
      - net
    depends_on:
      - spark-master
      - spark-worker1
      - spark-worker2

#  db:
#    container_name: pg_container
#    image: postgres
#    restart: always
#    environment:
#        POSTGRES_USER: "postgres"
#        POSTGRES_PASSWORD: "12345"
#        POSTGRES_DB: "db"
#        POSTGRES_HOST_AUTH_METHOD: trust
#    ports:
#      - "5432:5432"
#    networks:
#      - net
#
#volumes:
#  pg_data:

networks:
  net:
    driver: bridge